import "../styles/globals.css";
// import { Inter } from "next/font/google";
import Navbar from "./Navbar";
import Footer from "./Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Scissors App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Navbar />
      <main>{children}</main>
      <Footer />
    </div>
  );
}
